# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: basic
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

gazebo_ros_control/pid_gains:
  shoulder_pan_joint: {p: 0, i: 0.01, d: 0.0}
  shoulder_lift_joint: {p: 0.0, i: 0.01, d: 0.0}
  elbow_joint: {p: 0.0, i: 0.01, d: 0.0}
  wrist_1_joint: {p: 0.0, i: 0.01, d: 0.0}
  wrist_2_joint: {p: 0.0, i: 0.01, d: 0.0}
  wrist_3_joint: {p: 0.0, i: 0.01, d: 0.0}